from __future__ import annotations

import base64
import hashlib
import hmac as _hmac
import secrets
from typing import Optional, Tuple

try:
    from cryptography.fernet import Fernet
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2

    _crypto_available = True
except ImportError:
    _crypto_available = False
    Fernet = None  # type: ignore
    PBKDF2 = None  # type: ignore
    hashes = None  # type: ignore


def _ensure_crypto() -> None:
    """Verify that the cryptography package is available in the environment.

    Checks whether the optional ``cryptography`` dependency was successfully
    imported at module load time. If the package is missing, an informative
    ``ImportError`` is raised directing the user to install it.

    Returns:
        None.

    Raises:
        ImportError: If the ``cryptography`` package is not installed or
            could not be imported during module initialization.
    """
    if not _crypto_available:
        raise ImportError(
            "cryptography is required for encryption. Install with: pip install cryptography"
        )


def generate_key() -> bytes:
    """Generate a new Fernet symmetric encryption key.

    Creates a URL-safe base64-encoded 32-byte key suitable for use with
    the ``Fernet`` symmetric encryption scheme. The key is generated using
    cryptographically secure random bytes provided by the ``cryptography``
    library.

    Returns:
        A URL-safe base64-encoded key as ``bytes``, exactly 32 bytes
        before encoding, suitable for passing to ``encrypt`` and ``decrypt``.

    Raises:
        ImportError: If the ``cryptography`` package is not installed.
    """
    _ensure_crypto()
    return Fernet.generate_key()


def encrypt(value: str, key: bytes) -> str:
    """Encrypt a plaintext string using Fernet symmetric encryption.

    Encodes the given plaintext value using the provided Fernet key and
    returns the resulting ciphertext token as a UTF-8 string. The token
    includes a timestamp and can be verified for tampering during decryption.

    Args:
        value: The plaintext string to encrypt.
        key: A Fernet-compatible symmetric key as ``bytes``, typically
            generated by ``generate_key``.

    Returns:
        The encrypted ciphertext token as a URL-safe base64-encoded string.

    Raises:
        ImportError: If the ``cryptography`` package is not installed.
    """
    _ensure_crypto()
    f = Fernet(key)
    return f.encrypt(value.encode()).decode()


def decrypt(token: str, key: bytes) -> str:
    """Decrypt a Fernet-encrypted ciphertext token back to plaintext.

    Takes a ciphertext token previously produced by ``encrypt`` and decrypts
    it using the same Fernet symmetric key. The token is verified for
    integrity before decryption to detect any tampering.

    Args:
        token: The encrypted ciphertext token as a string, typically
            produced by the ``encrypt`` function.
        key: The Fernet-compatible symmetric key as ``bytes`` that was
            used to encrypt the original value.

    Returns:
        The decrypted plaintext string.

    Raises:
        ImportError: If the ``cryptography`` package is not installed.
        cryptography.fernet.InvalidToken: If the token is invalid, tampered
            with, or was encrypted with a different key.
    """
    _ensure_crypto()
    f = Fernet(key)
    return f.decrypt(token.encode()).decode()


def derive_key(
    password: str,
    salt: Optional[bytes] = None,
    length: int = 32,
    iterations: int = 600_000,
) -> Tuple[bytes, bytes]:
    """Derive a cryptographic key from a password using PBKDF2-HMAC-SHA256.

    Uses the PBKDF2 key derivation function with HMAC-SHA256 to produce a
    deterministic key from a password and salt. If no salt is provided, a
    cryptographically secure random 16-byte salt is generated automatically.
    The high default iteration count (600,000) provides resistance against
    brute-force attacks.

    Args:
        password: The password string from which to derive the key.
        salt: An optional salt as ``bytes``. If ``None``, a random 16-byte
            salt is generated using ``secrets.token_bytes``.
        length: The desired length of the derived key in bytes. Defaults
            to 32 (256 bits).
        iterations: The number of PBKDF2 iterations to perform. Higher
            values increase security but reduce performance. Defaults
            to 600,000.

    Returns:
        A tuple of ``(derived_key, salt)`` where ``derived_key`` is the
        derived key as ``bytes`` and ``salt`` is the salt used (either
        provided or auto-generated).

    Raises:
        ImportError: If the ``cryptography`` package is not installed.
    """
    _ensure_crypto()
    if salt is None:
        salt = secrets.token_bytes(16)
    kdf = PBKDF2(
        algorithm=hashes.SHA256(),
        length=length,
        salt=salt,
        iterations=iterations,
    )
    key = kdf.derive(password.encode())
    return key, salt


def sign_value(value: str, secret: str, algorithm: str = "sha256") -> str:
    """Create an HMAC-signed token from a value and secret.

    Computes an HMAC signature over the given value using the provided secret
    and hash algorithm. The value is base64url-encoded and concatenated with
    the hex digest of the signature, separated by a dot. This produces a
    compact, URL-safe signed token that can be verified later with
    ``unsign_value``.

    Args:
        value: The plaintext string value to sign.
        secret: The secret key string used for HMAC computation.
        algorithm: The hash algorithm name to use for HMAC. Defaults to
            ``"sha256"``. Any algorithm supported by ``hashlib`` is valid.

    Returns:
        A signed token string in the format ``"<base64url_payload>.<hex_signature>"``.
    """
    if isinstance(secret, str):
        secret = secret.encode()
    if isinstance(value, str):
        value = value.encode()

    signature = _hmac.new(secret, value, algorithm).hexdigest()
    payload = base64.urlsafe_b64encode(value).decode().rstrip("=")
    return f"{payload}.{signature}"


def unsign_value(
    signed: str, secret: str, algorithm: str = "sha256", max_age: Optional[int] = None
) -> str:
    """Verify and extract the original value from an HMAC-signed token.

    Parses a signed token produced by ``sign_value``, recomputes the HMAC
    signature using the same secret and algorithm, and compares it against
    the embedded signature using constant-time comparison to prevent timing
    attacks. If the signatures do not match, a ``BadSignature`` exception
    is raised.

    Args:
        signed: The signed token string in the format
            ``"<base64url_payload>.<hex_signature>"`` as produced by
            ``sign_value``.
        secret: The secret key string used for HMAC verification. Must
            match the secret used during signing.
        algorithm: The hash algorithm name used for HMAC. Must match the
            algorithm used during signing. Defaults to ``"sha256"``.
        max_age: Optional maximum age in seconds for the signed value.
            Reserved for future use; currently not enforced.

    Returns:
        The original plaintext string value that was signed.

    Raises:
        BadSignature: If the signature is invalid, the token format is
            malformed, or the secret does not match.
    """
    if isinstance(secret, str):
        secret = secret.encode()

    try:
        payload_b64, _, signature = signed.rpartition(".")
        value = base64.urlsafe_b64decode(payload_b64 + "==").decode()

        expected = _hmac.new(secret, value.encode(), algorithm).hexdigest()
        if not _hmac.compare_digest(expected, signature):
            raise BadSignature("Invalid signature")
    except Exception:
        raise BadSignature("Invalid signed value")

    return value


class BadSignature(Exception):
    """Exception raised when a signed value fails HMAC verification.

    This exception is raised by ``unsign_value`` when the cryptographic
    signature embedded in a signed token does not match the expected
    signature computed from the provided secret and algorithm. It indicates
    that the token has been tampered with, was produced with a different
    secret, or has a malformed structure.

    Attributes:
        message: A human-readable description of the verification failure.
    """

    pass
