from __future__ import annotations

from datetime import datetime, timedelta, timezone
from typing import Optional

from sillo.helpers import jwt as _jwt


class TokenForUser:
    """Create and manage JWT tokens bound to a user.

    Encapsulates the creation, encoding, and verification of JSON Web Tokens
    for a specific authenticated user. Supports generating both access and
    refresh tokens with configurable expiration times, as well as verifying
    token signatures and claims. The class wraps a low-level JWT helper to
    provide a user-centric interface that automatically includes the user's
    identity in the token subject claim.

    Attributes:
        user: The user object whose identity will be embedded in tokens.
        secret: The symmetric secret key used for signing and verifying tokens.
        algorithm: The JWT signing algorithm, defaults to HS256.
        issuer: Optional issuer claim to include in generated tokens.
        audience: Optional audience claim to include in generated tokens.
    """

    def __init__(
        self,
        user,
        secret: str,
        algorithm: str = "HS256",
        issuer: Optional[str] = None,
        audience: Optional[str] = None,
    ):
        """Initialize a TokenForUser instance with user context and signing config.

        Constructs a new token factory bound to the given user. All tokens
        generated by this instance will carry the user's identity in the
        subject claim and will be signed with the provided secret key and
        algorithm. Optional issuer and audience claims can be specified to
        add additional standard JWT claims for stricter token validation.

        Args:
            user: The user object to generate tokens for. Must have an
                ``identity`` property that returns a unique user identifier.
            secret: The symmetric secret key used for HMAC signing of tokens.
                Must be kept confidential and should be sufficiently random.
            algorithm: The JWT signing algorithm to use. Defaults to 'HS256'
                (HMAC with SHA-256). Other algorithms may be supported
                depending on the underlying JWT library configuration.
            issuer: Optional value for the 'iss' (issuer) JWT claim. When
                provided, tokens will include this value and verification
                will require a matching issuer claim.
            audience: Optional value for the 'aud' (audience) JWT claim. When
                provided, tokens will include this value and verification
                will require a matching audience claim.

        Returns:
            None: This constructor does not return a value.
        """
        self.user = user
        self.secret = secret
        self.algorithm = algorithm
        self.issuer = issuer
        self.audience = audience

    def _base_payload(self) -> dict:
        """Build the base JWT payload dictionary with common claims.

        Constructs a dictionary containing the standard JWT claims that are
        shared across all token types generated by this instance. The payload
        always includes the subject (user identity), issued-at timestamp, and
        token type. Optional issuer and audience claims are included when
        they were provided during initialization.

        Returns:
            dict: A dictionary containing the base JWT claims including
                'sub' (user identity string), 'iat' (issued-at UTC datetime),
                and 'typ' (token type, defaults to 'access'). May also
                contain 'iss' and 'aud' if configured.
        """
        now = datetime.now(timezone.utc)
        payload: dict = {"sub": str(self.user.identity), "iat": now, "typ": "access"}
        if self.issuer:
            payload["iss"] = self.issuer
        if self.audience:
            payload["aud"] = self.audience
        return payload

    def access_token(self, expires_in: Optional[timedelta] = None) -> str:
        """Generate a signed JWT access token for the bound user.

        Creates a short-lived access token with the 'access' type claim.
        Access tokens are intended for authorizing API requests and should
        have a relatively brief expiration time to limit the window of
        exposure if compromised. The default expiration is 15 minutes.

        Args:
            expires_in: Optional timedelta specifying how long the token
                should remain valid from the time of creation. If not
                provided, defaults to 15 minutes. Must be a positive
                timedelta value.

        Returns:
            str: A compact, URL-safe JWT access token string signed with
                the configured secret key and algorithm. The token contains
                the user identity, expiration time, and any configured
                issuer and audience claims.
        """
        payload = self._base_payload()
        payload["typ"] = "access"
        payload["exp"] = (
            datetime.now(timezone.utc) + expires_in
            if expires_in
            else datetime.now(timezone.utc) + timedelta(minutes=15)
        )
        return _jwt.encode(payload, self.secret, self.algorithm)

    def refresh_token(self, expires_in: Optional[timedelta] = None) -> str:
        """Generate a signed JWT refresh token for the bound user.

        Creates a long-lived refresh token with the 'refresh' type claim.
        Refresh tokens are used to obtain new access tokens without requiring
        the user to re-authenticate. They should have a longer expiration
        time than access tokens and are tracked in the database for rotation
        and revocation purposes. The default expiration is 7 days.

        Args:
            expires_in: Optional timedelta specifying how long the token
                should remain valid from the time of creation. If not
                provided, defaults to 7 days. Must be a positive
                timedelta value.

        Returns:
            str: A compact, URL-safe JWT refresh token string signed with
                the configured secret key and algorithm. The token contains
                the user identity, expiration time, and any configured
                issuer and audience claims.
        """
        payload = self._base_payload()
        payload["typ"] = "refresh"
        payload["exp"] = (
            datetime.now(timezone.utc) + expires_in
            if expires_in
            else datetime.now(timezone.utc) + timedelta(days=7)
        )
        return _jwt.encode(payload, self.secret, self.algorithm)

    def token_pair(
        self,
        access_expires: Optional[timedelta] = None,
        refresh_expires: Optional[timedelta] = None,
    ) -> dict:
        """Generate a complete access and refresh token pair for the bound user.

        Convenience method that creates both an access token and a refresh
        token in a single call, returning them as a dictionary suitable for
        sending directly to a client in an authentication response. The
        dictionary follows the standard OAuth2 token response format with
        an additional 'token_type' field set to 'bearer'.

        Args:
            access_expires: Optional timedelta for the access token's validity
                duration. If not provided, the access token defaults to
                15 minutes. See ``access_token`` for details.
            refresh_expires: Optional timedelta for the refresh token's validity
                duration. If not provided, the refresh token defaults to
                7 days. See ``refresh_token`` for details.

        Returns:
            dict: A dictionary containing 'access_token' (str), 'refresh_token'
                (str), and 'token_type' (str, always 'bearer'). This format
                is compatible with standard OAuth2 token response conventions.
        """
        return {
            "access_token": self.access_token(access_expires),
            "refresh_token": self.refresh_token(refresh_expires),
            "token_type": "bearer",
        }

    def verify(self, token: str) -> dict:
        """Verify a JWT token's signature, expiration, and registered claims.

        Performs full validation of the provided token including signature
        verification against the configured secret, expiration time checking,
        and validation of issuer and audience claims if configured. Raises
        an exception if any validation check fails.

        Args:
            token: The compact JWT token string to verify. Must be a
                properly formatted three-segment JWT encoded with the
                same algorithm and secret as this instance.

        Returns:
            dict: The decoded token payload as a dictionary containing all
                JWT claims such as 'sub', 'iat', 'exp', 'typ', and any
                optional claims like 'iss' and 'aud'.

        Raises:
            Exception: If the token signature is invalid, the token has
                expired, or the issuer/audience claims do not match the
                expected values configured on this instance.
        """
        return _jwt.decode(
            token,
            self.secret,
            algorithms=[self.algorithm],
            audience=self.audience,
            issuer=self.issuer,
        )

    def verify_no_expire(self, token: str) -> dict:
        """Verify a JWT token's signature and claims while ignoring expiration.

        Performs the same validation as ``verify`` except that the token's
        expiration time claim is not checked. This is useful for scenarios
        where an expired token's payload needs to be inspected, such as
        during refresh token rotation where the old token may be expired
        but its claims (like the token family) are still needed.

        Args:
            token: The compact JWT token string to verify. Must be a
                properly formatted three-segment JWT encoded with the
                same algorithm and secret as this instance.

        Returns:
            dict: The decoded token payload as a dictionary containing all
                JWT claims. The 'exp' claim is present in the returned
                dictionary but was not validated during decoding.

        Raises:
            Exception: If the token signature is invalid or the issuer/
                audience claims do not match the expected values. The
                expiration time is explicitly excluded from validation.
        """
        return _jwt.decode(
            token,
            self.secret,
            algorithms=[self.algorithm],
            audience=self.audience,
            issuer=self.issuer,
            options={"verify_exp": False},
        )

    @staticmethod
    def decode_unverified(token: str) -> dict:
        """Decode a JWT token's payload without verifying its signature.

        Extracts the payload claims from a JWT token without performing any
        cryptographic signature verification. This should only be used for
        inspecting token contents when the signature has already been
        verified through other means, or for debugging and logging purposes.
        Never trust the contents of an unverified token for authorization.

        Args:
            token: The compact JWT token string to decode. Must be a
                properly formatted three-segment JWT string.

        Returns:
            dict: The decoded token payload as a dictionary containing all
                JWT claims. The signature has NOT been verified, so these
                values should not be trusted for security decisions.

        Raises:
            Exception: If the token string is malformed or cannot be
                decoded as a valid JWT structure.
        """
        return _jwt.decode_without_verification(token)

    @staticmethod
    def get_unverified_header(token: str) -> dict:
        """Extract the header claims from a JWT token without verification.

        Parses the header segment of a JWT token and returns its claims
        as a dictionary. The header typically contains the algorithm ('alg')
        and token type ('typ') claims. No signature verification is performed.
        This is useful for inspecting which algorithm was used to sign a
        token before performing full verification.

        Args:
            token: The compact JWT token string whose header should be
                extracted. Must be a properly formatted three-segment
                JWT string.

        Returns:
            dict: The decoded JWT header as a dictionary, typically containing
                'alg' (the signing algorithm) and 'typ' (the token type).

        Raises:
            Exception: If the token string is malformed or the header
                segment cannot be decoded as valid JSON.
        """
        return _jwt.get_unverified_header(token)
