"""
sillo.record.transactions — Database transaction API with savepoints.

Provides a context-manager-based transaction API and manual begin/commit/rollback.

Usage::

    async with transaction():
        await user.save()
        await order.save()

    async with transaction() as tx:
        await user.save()
        async with tx.savepoint():
            await risky_operation()  # rolled back on failure
        await order.save()
"""

from __future__ import annotations

import logging
from contextlib import asynccontextmanager
from typing import Annotated, Optional

from tortoise import connections
from typing_extensions import Doc

logger = logging.getLogger("sillo.record.transactions")


@asynccontextmanager
async def transaction(
    connection_name: Annotated[str, Doc("Connection name.")] = "default",
):
    """Execute a block within a database transaction.

    Commits on clean exit, rolls back on exception.

    Usage::

        async with transaction():
            await user.save()
            await order.save()
    """
    conn = connections.get(connection_name)
    try:
        async with conn._in_transaction() as tx:
            yield TransactionContext(conn, tx)
    except Exception:
        logger.exception("Transaction rolled back")
        raise


class TransactionContext:
    """Context for manual transaction management."""

    def __init__(self, conn, tx):
        """Init

        Args:
            conn: [description]
            tx: [description]

        Returns:
            [description]

        Raises:
            [description]
        """
        self._conn = conn
        self._tx = tx

    @asynccontextmanager
    async def savepoint(self):
        """Open a nested savepoint inside this transaction.

        The savepoint is released on clean exit and rolled back to on
        exception, leaving the enclosing transaction alive either way — an
        exception raised inside the block propagates, but only the work done
        inside the block is undone.

        Savepoints nest, and each one gets a name generated by the driver, so
        two savepoints open at the same time do not collide::

            async with transaction() as tx:
                await user.save()
                async with tx.savepoint() as sp:
                    await risky()
                    async with sp.savepoint():
                        await riskier()

        Yields:
            A :class:`TransactionContext` for the savepoint, so blocks can be
            nested further.
        """
        async with self._tx._in_transaction() as nested:
            yield TransactionContext(self._conn, nested)


async def begin(connection_name: str = "default") -> None:
    """Manually begin a transaction."""
    conn = connections.get(connection_name)
    await conn.execute_query("BEGIN")


async def commit(connection_name: str = "default") -> None:
    """Manually commit a transaction."""
    conn = connections.get(connection_name)
    await conn.execute_query("COMMIT")


async def rollback(connection_name: str = "default") -> None:
    """Manually rollback a transaction."""
    conn = connections.get(connection_name)
    await conn.execute_query("ROLLBACK")
